/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/cuadroCanva.glb
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF,Text } from '@react-three/drei'
import { MeshBasicMaterial,TextureLoader } from 'three';
import { useSelector } from 'react-redux';

export function CuadroCanva(props) {
  const { nodes, materials } = useGLTF('models/cuadroCanva.glb')
  const sumaX=1.6;
  const frame=useSelector(state=>state.buildFrame)
  //Textura del canvas
  const texture = new TextureLoader().load('models/texFrame.png');
  const materialtext = new MeshBasicMaterial({ map: texture})
  //Color de los listones
  const colorFrame=useSelector(state=>state.colorFrame)
  var material=new THREE.MeshBasicMaterial({color:colorFrame.materials})
  nodes.liston005.material.color.r=material.color.r;
  nodes.liston005.material.color.g=material.color.g;
  nodes.liston005.material.color.b=material.color.b;
  const zoomFactor = 2.25;
  return (
    <group {...props} dispose={null} scale={[zoomFactor, zoomFactor, zoomFactor]}>
      <pointLight intensity={0.7} decay={2} position={[3, -5, 3.06]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={1} decay={2} position={[-1.62, 0.05, 3.06]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tapa.geometry} material={materialtext} position={[-1.63+sumaX, 0.12, 0.19]} rotation={[Math.PI/2, Math.PI, -3.14]} scale={[0.8, 0.1, 0.8]} />
      <mesh geometry={nodes.liston006.geometry} material={nodes.liston005.material} position={[-1.73+sumaX, 0.92, 0.09]} rotation={[1.57, 1.57, 0]} scale={[0.1, 0.1, 0.8]} />
      <mesh geometry={nodes.liston007.geometry} material={nodes.liston005.material} position={[-2.43+sumaX, 0.22, 0.09]} rotation={[-Math.PI / 2, 0, -3.14]} scale={[0.1, 0.1, 0.8]} />
      <mesh geometry={nodes.liston005.geometry} material={nodes.liston005.material} position={[-1.53+sumaX, -0.68, 0.09]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.1, 0.1, 0.8]} />
      <mesh geometry={nodes.liston008.geometry} material={nodes.liston005.material} position={[-0.83+sumaX, 0.02, 0.09]} rotation={[1.57, 0, 0]} scale={[0.1, 0.1, 0.8]} />
      <group>
        <Text
          fontSize={0.1} // Tamaño de fuente
          font="" // Ruta de la fuente
          color="black" // Color del texto
          position={[1.1, 0.1, 0.13]} // Posición del texto en el espacio 3D
          rotation={[0, 0, 0]} // Rotación del texto
        >
          Alto:
        </Text>
        <Text
          fontSize={0.1} // Tamaño de fuente
          font="" // Ruta de la fuente
          color="black" // Color del texto
          position={[1.2, 0, 0.13]} // Posición del texto en el espacio 3D
          rotation={[0, 0, 0]} // Rotación del texto
        >{frame.frame.alturaC} cm</Text>
      </group>
      <Text
        fontSize={0.1} // Tamaño de fuente
        font="" // Ruta de la fuente
        color="black" // Color del texto
        position={[0, -1, 0.13]} // Posición del texto en el espacio 3D
        rotation={[0, 0, 0]} // Rotación del texto
      >
        Ancho: {frame.frame.anchoC} cm
      </Text>
    </group>
  )
}

useGLTF.preload('models/cuadroCanva.glb')
